// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlltctolzyymffrrdjfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsbHRjdG9senl5bWZmcnJkamZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDI2NTAsImV4cCI6MjA2NzU3ODY1MH0.LAbcMfkbZKA8Yl9EMmfe-UZcVHzHYyJpxrrGjRfvSkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});